---
  - name: nagios libraries and dependecies (Ubuntu)
    tags: ubuntu,dependecies,libraries
    apt:
      name:
        - autoconf
        - libc6
        - gcc
        - make
        - wget
        - unzip
        - apache2
        - php
        - libapache2-mod-php
        - libgd-dev
        - openssl
        - libssl-dev
        - bc
        - gawk
        - dc
        - build-essential
        - snmp
        - libnet-snmp-perl
        - gettext
        - python
        - python-pip
      state: latest

  - name: passlib package
    pip:
      name: passlib

  - name: nagios directory PATH
    file:
      path: ~/nagios
      state: directory

  - name: downloading nagios
    unarchive:
      src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      dest: ~/nagios
      remote_src: yes
      mode: 0777
      owner: root
      group: root

  - name: downloading nagios plugins
    unarchive:
      src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
      dest: ~/nagios
      remote_src: yes
      mode: 0777
      owner: root
      group: root

  - name: install, compile, adding users and groups
    shell: |
      cd ~/nagios/nagioscore-*
      ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      make all
      make install-groups-users
      usermod -a -G nagios www-data
      make install
      make install-daemoninit
      make install-commandmode
      make install-config
      make install-webconf
      a2enmod rewrite
      a2enmod cgi

  - name: complie and install plugins
    shell: |
      cd ~/nagios/nagios-plugins*
      ./tools/setup
      ./configure
      make
      make install

  - name: Adding users to nagios
    command: htpasswd -bc /usr/local/nagios/etc/htpasswd.users admin admin

  - name: Nagios Start/Enable Check
    service:
      name: nagios
      state: restarted
      enabled: true

  - name: Apache/httpd Start/Enable Check
    service:
      name: apache2
      state: restarted
      enabled: true
